name: lint_rules
description: Lint rules for Dart&Flutter projects.
version: 0.0.1
homepage: https://github.com/NM4ik/handbook

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  